AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  Code to deploy aws infrastructure for 2 microservices
  focus in order and payment services

Globals:
  # base configuration for all lambdas
  Function:
    Runtime: go1.x
    Timeout: 5
    Architectures:
      - x86_64

Resources:
  # Configuration for API
  APIGatewayApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: Dev
      Models:
        Order:
          type: object
          required:
            - UserID
            - Item
            - Quantity
            - TotalPrice
          properties:
            UserID:
              type: string
            Item:
              type: string
            Quantity:
              type: integer
            TotalPrice:
              type: number
        Payment:
          type: object
          required:
            - OrderID
            - Status
          properties:
            OrderID:
              Type: string
            Status:
              type: string

  # Deploy all the functions
  OrderEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Order_Event_Lambda
      CodeUri: services/functions/order_event
      Handler: order_event_lambda

  OrderApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Order_API_Lambda
      CodeUri: services/functions/order_api
      Handler: order_api_lambda
      Events:
        ApiEvent:
          Type: Api
          Properties:
            RestApiId: APIGatewayApi
            Path: /order
            Method: POST
            RequestModel:
              Model: Order
              Required: true
              ValidateBody: true

  PaymentEventFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Payment_Event_Lambda
      CodeUri: services/functions/payment_event
      Handler: payment_event_lambda

  PaymentApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Payment_API_Lambda
      CodeUri: services/functions/payment_api
      Handler: payment_api_lambda
